#NOTA
version: 2
jobs:
  test-github-super-linter:
    working_directory: ~/main
    docker:
      - image: github/super-linter:latest
    environment:
      RUN_LOCAL: "true"
      DEFAULT_WORKSPACE: "/root/main"
      VALIDATE_ALL_CODEBASE: "true"
      VALIDATE_CLOUDFORMATION: "true"
      VALIDATE_DOCKER: "true"
      VALIDATE_EDITORCONFIG: "true"
      VALIDATE_JSON: "true"
      VALIDATE_MD: "true"
      VALIDATE_YAML: "true"
      VALIDATE_HTML: "true"
      VALIDATE_CSS: "true"
      VALIDATE_JAVASCRIPT_ES: "true"
    steps:
      - checkout:
          path: ~/main
      - run:
          name: testing
          command: bash /action/lib/linter.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - test-github-super-linter
