# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  super-linter: github/super-linter@v3
jobs:
  test-github-super-linter:
    working_directory: ~/main
    docker:
      - image: github/super-linter@v3
    environment:
      RUN_LOCAL: "true"
      DEFAULT_WORKSPACE: "/root/main"
      VALIDATE_ALL_CODEBASE: "true"
      VALIDATE_CLOUDFORMATION: "true"
      VALIDATE_DOCKER: "true"
      VALIDATE_EDITORCONFIG: "true"
      VALIDATE_JSON: "true"
      VALIDATE_MD: "true"
      VALIDATE_YAML: "true"  
    steps:
      - checkout:
          path: ~/main
      - run:
          name: testing
          command: bash /action/lib/linter.sh
